### ISSUE TITLE
How can i login

### ISSUE THREAD

**Issue by GJHe** [programmersommer/Blog#1]
I have connected the database, there is no login form in the database. Can you tell me how your blog project works?

**Comment by programmersommer** [comment]
Hi! You can use attached database. It is located in folder Blog/App_Data. Inside web.config file you can find connection string to this file.     
     
    `<add name="blogdbEntities" connectionString="metadata=res://*/App_Code.blogpostsModel.csdl|res://*/App_Code.blogpostsModel.ssdl|res://*/App_Code.blogpostsModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\blogdb.mdf;Integrated Security=True;MultipleActiveResultSets=True&quot;" providerName="System.Data.EntityClient" />`

Not every hosting working well with attached databases. I recommend you to create database with similar structure and change connection string. Also inside web.config file you can find credentials to blog admin part. 

`<user name="1" password="1" />`

Forms authentication used. It is recommended only for local network, not for internet.

**Comment by GJHe** [comment]
vervy thanks, i find <user name="1" password="1" />
now i think it has other problems

Server error in the "/Blog-master" application.

Unable to find resource.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) may have been removed, or its name has changed, or is temporarily unavailable. Please check the URL below and make sure it is spelled correctly.

Requested URL: /Blog-master/default.aspx

    <defaultDocument>
      <files>
        <clear />
        <add value="Default.aspx" />
      </files>
    </defaultDocument>





but i not find Default.aspx      oh my gad

**Comment by programmersommer** [comment]
Just change Default.aspx to blog.aspx

**Comment by GJHe** [comment]
i do it .but  it also have problems, i have give up
